#!/bin/sh
# postrm script for tpfand
set -e

case "$1" in
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|purge)
	# restart tpfand to reload profiles
	echo Restarting tpfand...
	invoke-rc.d tpfand restart
	true	
    ;;   
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


